### PR TITLE
[OpenCL] Fixes GatherOP on SYCL devices

### LINKED ISSUE #43: FAIL: //tensorflow/python/kernel_tests:gather_op_test
## System Info

```
  Name:						 Hawaii
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 1912.5 (VM)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 2.0 AMD-APP (1912.5)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_khr_gl_depth_images cl_ext_atomic_counters_32 cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_subgroups cl_khr_gl_event cl_khr_depth_images cl_khr_mipmap_image cl_khr_mipmap_image_writes

```
ComputeCpp 0.2.0

## To reproduce
```
bazel test --config=sycl --test_tag_filters=local,-benchmark-test --local_test_jobs=4 -k --test_lang_filters=cc,py --action_env=LD_PRELOAD=/usr/lib/libOpenCL.so.1 --test_timeout 300,750,1200,3600 //tensorflow/python/kernel_tests:gather_op_test
```

## Error
```
FAIL: testHigherRank (__main__.GatherTest)
...
FAIL: testScalar1D (__main__.GatherTest)
...
FAIL: testScalar2D (__main__.GatherTest)
...
FAIL: testSimpleTwoD32 (__main__.GatherTest)
...
Arrays are not equal

(mismatch 100.0%)
 x: array([[  0.,   1.,   2.],
       [ 12.,  13.,  14.],
       [  0.,   1.,   2.],
       [  6.,   7.,   8.]], dtype=float32)
 y: array([[  5.952276e-38,   0.000000e+00,   6.025583e-44],
       [  4.728368e+27,   1.418165e-19,   6.728976e+08],
       [  5.952276e-38,   0.000000e+00,   6.025583e-44],
       [  1.849687e+20,   2.053673e-19,   7.006238e+22]], dtype=float32)
```

### PR DESCRIPTION
**Pull request by jwlawson**
Ensures that both GatherFunctor and UnsortedSegmentSumFunctor are actually computed on the device, not CPU.
Unifies CPU and SYCL versions of UnsortedSegmentSumFunctor.
Fixes #43.

### CODE REVIEW

File: tensorflow/core/kernels/segment_reduction_ops.cc [hunk 1]
```diff
@@ -232,32 +232,29 @@ REGISTER_COMPLEX_CPU_KERNELS_ALL(complex128);
...
-      Index j = internal::SubtleMustCopy(segment_ids(i));
-      OP_REQUIRES(ctx, FastBoundsCheck(j, output_rows),
-                  errors::InvalidArgument(
-                      "segment_ids", SliceDebugString(segment_ids_shape, i),
-                      " = ", j, " is out of range [0, ", output_rows, ")"));
-      output.template chip<0>(j) += data_flat.template chip<0>(i);
-    }
+template <typename Device, typename T, typename Index>
+void UnsortedSegmentSumFunctor<Device, T, Index>::operator()(
+    OpKernelContext* ctx, const Device& d, const Index output_rows,
```
Comment (lukeiwanski) [inline tensorflow/core/kernels/segment_reduction_ops.cc]: can you clang format it with Google style?

**Review by lukeiwanski — APPROVED** [review]
